name: Data preprocessing Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        pip install -r ./data/requirements.txt  
        python -m pip install --upgrade pip
        

    - name: Run Pipeline
      run: |
        chmod u+r+x ./project/pipeline.sh
        ./project/pipeline.sh
