name: Data Pipeline

on:
  push:
      paths:
            - data/**
            - project/**

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Pipeline
      run: |
        cd project
        chmod +x pipeline.sh
        ./pipeline.sh
